# Generated by Django 2.2.11 on 2020-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporary_username', models.CharField(max_length=150)),
                ('user_registration_code', models.CharField(help_text='For your email was sent registration code,please enter this code in the field', max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='registration_number',
        ),
    ]
