# Generated by Django 2.2.11 on 2020-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200327_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryRegistrationModel',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='user_registration_code',
            field=models.CharField(default=None, help_text='For your email was sent registration code,please enter this code in the field', max_length=8),
            preserve_default=False,
        ),
    ]
